app = "wa-agent-app"
primary_region = "bom"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 80

[[mounts]]
  source = "wa_uploads"
  destination = "/app/static/uploads"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
